word_align(size) = 4 * cld(size, 4)

include("parsing/table_records.jl")
include("parsing/font_header.jl")
include("parsing/maximum_profile.jl")
include("parsing/cmap.jl")
include("parsing/metrics.jl")
include("parsing/loca.jl")
include("parsing/glyf.jl")
include("parsing/coverage.jl")
include("parsing/script.jl")
include("parsing/features.jl")
include("parsing/lookup.jl")
include("parsing/classes.jl")
include("parsing/contextual_tables.jl")
include("parsing/device.jl")
include("parsing/gdef.jl")
include("parsing/gpos.jl")
include("parsing/gsub.jl")
include("parsing/variation.jl")
