name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7', '1.8', '1.9', 'nightly']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ENV_KEY }}
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - uses: actions/cache@v3
        name: Cache Google Fonts data
        with:
          path: test/google_fonts
          key: ${{ runner.OS }}-google-fonts-cache-${{ hashFiles('test/google_fonts/**') }}
          restore-keys: ${{ runner.os }}-google-fonts-cache-
      - run: julia --color=yes --project -e 'using Pkg;
               Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:serenity4/Graphics"));
               Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:JuliaRegistries/General"));
               Pkg.instantiate()'
      - run: julia --color=yes --project -e 'using Pkg; Pkg.test(coverage = true)'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
    env:
      JULIA_PKG_USE_CLI_GIT: true
